id: A93F10D9F
base_file: f8C91.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:36:42.050813
  last_modified_at: 2022-05-31 06:36:42.050820
